spring:
  application:
    name: EurekaServer

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false  # сам не регистрируется в себе
    fetch-registry: false        # не получает реестр (он сам — источник)
  server:
    wait-time-in-ms-when-sync-empty: 0